Use vanilla Timeout() functions instead of the Meteor versions
Using Meteor.setTimeout() causes errors when the computation is invalidated from inside a simulation:
  Error: Can't set timers inside simulations

On the client setTimeout() can be used directly to avoid this.